### PR TITLE
Pull Request for Ruby on Rails capstone project - Budget app

### PR DESCRIPTION
**Pull request by chuaindia**
In this PR the followings are incorporated :

- Splash screen
- [ ]        A simple page with the name of the app and links to the sign up and log in pages.

- Sign up and log in pages
- [ ]        The user should be able to register in the app with full name, email and password (all mandatory).
- [ ]        The user can log into the app using email and password.
- [ ]        If the user is not logged in, they can't access pages that require the user to be logged in. 

- Home page (categories page --- Here named as groups)
       
- [ ]         For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that 
- [ ]        category.
- [ ]        When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- [ ]       There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
     
- [ ]       For a given category, the list of transactions is presented, ordered by the most recent.
- [ ]       At the top of the page the user could see the total amount for the category (sum of all of the amounts of the 
            transactions in that category.
- [ ]       There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- [ ]       When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
   
- [ ]         The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- [ ]        The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- [ ]        When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
     
- [ ]         The user fills out a form to create a new transaction with:
- [ ]         name (mandatory)
- [ ]         amount (mandatory)
- [ ]         categories (mandatory at least one)
- [ ]         The user clicks (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that 
- [ ]         category.
- [ ]          When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

- Testing requirements
     
- [ ]        Create unit and integration tests for all the most important components of your RoR application.

The loom video link :   https://www.loom.com/share/8cb3175e5c07456a8e902d6bd9639749

### CODE REVIEW

**Review by Mihndim2020 — COMMENTED** [review]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi @chuaindia,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure your implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._
- [x] Please you have submitted a pull request with no zero file changes. For us to provide you with an effective review, please kindly merge your `deployment branch to the development branch`, then raise a pull request from the `development branch to the main branch` as this will make your files accessible for us to perform a review. You can also follow this [link ](https://devcenter.heroku.com/articles/getting-started-with-rails7)to help with the deployment of your project. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by chuaindia** [comment]
@Mihndim2020, I am really perplexed. I did the same thing earlier. But another reviewer made the following comment : 

I  am attaching the screenshot.
Screenshot (237)

Please help me. I am really feeling frustrated.

**Comment by chuaindia** [comment]
I am sending the same pull request again with this comment.

**Comment by chuaindia** [comment]
I have got vivid help from @andersonlebon . I open a pull request following his guidance. I am very much thankful to Anderson for his invaluable guidance. It helps me to come out from imposter syndrome. The pull request contains all the changes required from the reviewers. I am attaching here the new pull request link: https://github.com/chuaindia/ror_capstone_budget_app/pull/13/

**Pull request merged**
